"""add crawler config table

Revision ID: 1067e3e0c5f4
Revises: b1990a71e580
Create Date: 2025-12-05 09:48:48.074636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1067e3e0c5f4'
down_revision = 'b1990a71e580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('headers_json', sa.Text(), nullable=True),
    sa.Column('list_selector', sa.String(length=256), nullable=True),
    sa.Column('title_selector', sa.String(length=256), nullable=True),
    sa.Column('url_selector', sa.String(length=256), nullable=True),
    sa.Column('cover_selector', sa.String(length=256), nullable=True),
    sa.Column('source_selector', sa.String(length=256), nullable=True),
    sa.Column('date_selector', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('crawler')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('script_path', sa.VARCHAR(length=256), nullable=True),
    sa.Column('base_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('config', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('crawler_config')
    # ### end Alembic commands ###
