"""add collection models

Revision ID: 14f0a95bb439
Revises: c505240b7234
Create Date: 2025-12-04 10:18:48.465227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f0a95bb439'
down_revision = 'c505240b7234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('cover', sa.String(length=1024), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('deep_collected', sa.Boolean(), nullable=True),
    sa.Column('deep_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_item_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_item_url'), ['url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_item_url'))
        batch_op.drop_index(batch_op.f('ix_collection_item_keyword'))

    op.drop_table('collection_item')
    # ### end Alembic commands ###
