"""update crawlrule

Revision ID: 6e07c2659f63
Revises: c2c7cc1602c5
Create Date: 2025-12-04 17:18:46.860392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e07c2659f63'
down_revision = 'c2c7cc1602c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('match_type', sa.String(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_crawl_rule_site'))
        batch_op.create_index(batch_op.f('ix_crawl_rule_site'), ['site'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_rule_site'))
        batch_op.create_index(batch_op.f('ix_crawl_rule_site'), ['site'], unique=1)
        batch_op.drop_column('match_type')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
