"""add crawl rules

Revision ID: 89fec29a5465
Revises: 14f0a95bb439
Create Date: 2025-12-04 15:21:25.880594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89fec29a5465'
down_revision = '14f0a95bb439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=256), nullable=True),
    sa.Column('title_xpath', sa.String(length=1024), nullable=True),
    sa.Column('content_xpath', sa.String(length=2048), nullable=True),
    sa.Column('headers_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_rule_site'), ['site'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_rule_site'))

    op.drop_table('crawl_rule')
    # ### end Alembic commands ###
