"""add rule_id to collection_item

Revision ID: a7fe9e86e6d4
Revises: 533426eb12e0
Create Date: 2025-12-04 17:39:29.223268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fe9e86e6d4'
down_revision = '533426eb12e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_collection_item_rule_id_crawl_rule', 'crawl_rule', ['rule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_collection_item_rule_id_crawl_rule', type_='foreignkey')
        batch_op.drop_column('rule_id')

    # ### end Alembic commands ###
