"""Add auth models

Revision ID: c505240b7234
Revises: 0986516a2aae
Create Date: 2025-12-03 21:36:37.092802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c505240b7234'
down_revision = '0986516a2aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_setting_key'), ['key'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_foreign_key('fk_user_role_id', 'role', ['role_id'], ['id'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint('fk_user_role_id', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('role_id')
        batch_op.drop_column('name')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_setting_key'))

    op.drop_table('system_setting')
    op.drop_table('role')
    # ### end Alembic commands ###
